// <auto-generated />
using System;
using AntiqueStore.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AntiqueStore.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AntiqueStore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<int?>("FormatId");

                    b.Property<string>("Language");

                    b.Property<int>("Page");

                    b.Property<int>("Price");

                    b.Property<string>("PublicationDate");

                    b.Property<int?>("QualityId");

                    b.Property<int>("Quantity");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("QualityId");

                    b.ToTable("Books");

                    b.HasData(
                        new { Id = 1, Author = "Andre Aciman", Language = "English", Page = 256, Price = 6999, PublicationDate = "03/Apr/2018", Quantity = 2, Title = "Call Me By Your Name" },
                        new { Id = 2, Author = "Stephen King", Language = "English", Page = 160, Price = 2399, PublicationDate = "30/Oct/2018", Quantity = 1, Title = "Elevation" }
                    );
                });

            modelBuilder.Entity("AntiqueStore.Models.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Binding");

                    b.HasKey("Id");

                    b.ToTable("Formats");

                    b.HasData(
                        new { Id = 1, Binding = "Paperback" },
                        new { Id = 2, Binding = "Hardcover" }
                    );
                });

            modelBuilder.Entity("AntiqueStore.Models.Quality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Condition");

                    b.HasKey("Id");

                    b.ToTable("Qualities");

                    b.HasData(
                        new { Id = 1, Condition = "Good" },
                        new { Id = 2, Condition = "Bad" }
                    );
                });

            modelBuilder.Entity("AntiqueStore.Models.Book", b =>
                {
                    b.HasOne("AntiqueStore.Models.Format", "Format")
                        .WithMany("Books")
                        .HasForeignKey("FormatId");

                    b.HasOne("AntiqueStore.Models.Quality", "Quality")
                        .WithMany("Books")
                        .HasForeignKey("QualityId");
                });
#pragma warning restore 612, 618
        }
    }
}
