// <auto-generated />
using System;
using AntiqueStore.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AntiqueStore.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AntiqueStore.Models.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Description");

                    b.Property<double>("Price");

                    b.Property<int>("PublicationDate");

                    b.Property<string>("Publisher");

                    b.Property<int>("Quantity");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("AntiqueStore.Models.Dimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId");

                    b.Property<long?>("BookId1");

                    b.Property<string>("Size");

                    b.Property<double>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("BookId1");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("AntiqueStore.Models.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Binding");

                    b.Property<int>("BookId");

                    b.Property<long?>("BookId1");

                    b.Property<int>("Pages");

                    b.HasKey("Id");

                    b.HasIndex("BookId1");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("AntiqueStore.Models.Dimension", b =>
                {
                    b.HasOne("AntiqueStore.Models.Book")
                        .WithMany("Dimensions")
                        .HasForeignKey("BookId1");
                });

            modelBuilder.Entity("AntiqueStore.Models.Format", b =>
                {
                    b.HasOne("AntiqueStore.Models.Book")
                        .WithMany("Formats")
                        .HasForeignKey("BookId1");
                });
#pragma warning restore 612, 618
        }
    }
}
